package entities

import (
	"errors"
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Category represents a product category in the e-commerce system
type Category struct {
	ID          primitive.ObjectID   `json:"id,omitempty" bson:"_id,omitempty"`
	Name        string               `json:"name" bson:"name"`
	Description string               `json:"description" bson:"description"`
	Slug        string               `json:"slug" bson:"slug"`
	ParentID    primitive.ObjectID   `json:"parent_id,omitempty" bson:"parent_id,omitempty"`
	Level       int                  `json:"level" bson:"level"`
	Path        []primitive.ObjectID `json:"path" bson:"path"`
	Children    []Category           `json:"children,omitempty" bson:"-"`
	CreatedAt   time.Time            `json:"created_at" bson:"created_at"`
	UpdatedAt   time.Time            `json:"updated_at" bson:"updated_at"`
}

// NewCategory creates a new category (ID will be auto-generated by MongoDB)
func NewCategory(name, description, slug string, parentID primitive.ObjectID) *Category {
	now := time.Now()
	level := 1
	path := []primitive.ObjectID{}

	// If this is a subcategory, set level to 2 or more
	if !parentID.IsZero() {
		level = 2 // This will be updated when saved to reflect the actual level
		path = []primitive.ObjectID{parentID}
	}

	return &Category{
		Name:        name,
		Description: description,
		Slug:        slug,
		ParentID:    parentID,
		Level:       level,
		Path:        path,
		Children:    []Category{},
		CreatedAt:   now,
		UpdatedAt:   now,
	}
}

// AddChild adds a child category to this category
func (c *Category) AddChild(child *Category) error {
	if child == nil {
		return errors.New("child category cannot be nil")
	}

	// Set the parent ID and update level
	child.ParentID = c.ID
	child.Level = c.Level + 1

	// Update the path to include all ancestors
	child.Path = append(append([]primitive.ObjectID{}, c.Path...), c.ID)

	// Add to children collection
	c.Children = append(c.Children, *child)
	c.UpdatedAt = time.Now()

	return nil
}

// Update updates the category details
func (c *Category) Update(name, description, slug string) {
	c.Name = name
	c.Description = description
	c.Slug = slug
	c.UpdatedAt = time.Now()
}

// IsRoot checks if this category is a root category (no parent)
func (c *Category) IsRoot() bool {
	return c.ParentID.IsZero()
}

// IsLeaf checks if this category is a leaf category (no children)
func (c *Category) IsLeaf() bool {
	return len(c.Children) == 0
}

// GetAncestorIDs returns all ancestor IDs including this category's ID
func (c *Category) GetAncestorIDs() []primitive.ObjectID {
	result := append(append([]primitive.ObjectID{}, c.Path...), c.ID)
	return result
}
