package entities

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// NotificationType represents the type of notification
type NotificationType string

const (
	NotificationTypeOrderStatus NotificationType = "order_status"
	NotificationTypePayment     NotificationType = "payment"
	NotificationTypeShipping    NotificationType = "shipping"
	NotificationTypeSystem      NotificationType = "system"
)

// NotificationStatus represents the status of a notification
type NotificationStatus string

const (
	NotificationStatusUnread   NotificationStatus = "unread"
	NotificationStatusRead     NotificationStatus = "read"
	NotificationStatusArchived NotificationStatus = "archived"
)

// Notification represents a notification in the system
type Notification struct {
	ID primitive.ObjectID `json:"id,omitempty"`
	UserID primitive.ObjectID `json:"user_id"`
	Type      NotificationType       `json:"type"`
	Title     string                 `json:"title"`
	Message   string                 `json:"message"`
	Status    NotificationStatus     `json:"status"`
	Data      map[string]interface{} `json:"data,omitempty"`
	CreatedAt time.Time              `json:"created_at"`
	UpdatedAt time.Time              `json:"updated_at"`
	ReadAt    *time.Time             `json:"read_at,omitempty"`
}

// NotificationTemplate represents a template for generating notifications
type NotificationTemplate struct {
	ID primitive.ObjectID `json:"id,omitempty"`
	Name            string           `json:"name"`
	Type            NotificationType `json:"type"`
	TitleTemplate   string           `json:"title_template"`
	MessageTemplate string           `json:"message_template"`
	Active          bool             `json:"active"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

// NewNotification creates a new notification (ID will be auto-generated by repository)
func NewNotification(userID primitive.ObjectID, notificationType NotificationType, title, message string, data map[string]interface{}) *Notification {
	now := time.Now()
	return &Notification{
		UserID:    userID,
		Type:      notificationType,
		Title:     title,
		Message:   message,
		Status:    NotificationStatusUnread,
		Data:      data,
		CreatedAt: now,
		UpdatedAt: now,
	}
}

// MarkAsRead marks a notification as read
func (n *Notification) MarkAsRead() {
	now := time.Now()
	n.Status = NotificationStatusRead
	n.ReadAt = &now
	n.UpdatedAt = now
}

// MarkAsArchived marks a notification as archived
func (n *Notification) MarkAsArchived() {
	n.Status = NotificationStatusArchived
	n.UpdatedAt = time.Now()
}

// NewNotificationTemplate creates a new notification template
func NewNotificationTemplate(name string, notificationType NotificationType, titleTemplate, messageTemplate string) *NotificationTemplate {
	now := time.Now()
	return &NotificationTemplate{
		Name:            name,
		Type:            notificationType,
		TitleTemplate:   titleTemplate,
		MessageTemplate: messageTemplate,
		Active:          true,
		CreatedAt:       now,
		UpdatedAt:       now,
	}
}
