package entities

import (
	"errors"
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// WishlistItem represents a product in a user's wishlist
type WishlistItem struct {
	ID        primitive.ObjectID `json:"id,omitempty"`
	ProductID primitive.ObjectID `json:"product_id"`
	AddedAt   time.Time          `json:"added_at"`
}

// Wishlist represents a user's wishlist in the e-commerce system
type Wishlist struct {
	ID primitive.ObjectID `json:"id,omitempty"`
	UserID primitive.ObjectID `json:"user_id"`
	Items     []*WishlistItem `json:"items"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// NewWishlist creates a new wishlist (ID will be auto-generated by repository)
func NewWishlist(userID primitive.ObjectID) *Wishlist {
	now := time.Now()
	return &Wishlist{
		UserID:    userID,
		Items:     []*WishlistItem{},
		CreatedAt: now,
		UpdatedAt: now,
	}
}

// AddItem adds a product to the wishlist
func (w *Wishlist) AddItem(productID primitive.ObjectID) (*WishlistItem, error) {
	// Check if the item already exists in the wishlist
	for _, item := range w.Items {
		if item.ProductID == productID {
			return nil, errors.New("item already exists in wishlist")
		}
	}

	// Add new item
	item := &WishlistItem{
		ProductID: productID,
		AddedAt:   time.Now(),
	}

	w.Items = append(w.Items, item)
	w.UpdatedAt = time.Now()

	return item, nil
}

// RemoveItem removes a product from the wishlist by item ID
func (w *Wishlist) RemoveItem(itemID primitive.ObjectID) error {
	for i, item := range w.Items {
		if item.ID == itemID {
			// Remove item by replacing it with the last item and truncating the slice
			lastIndex := len(w.Items) - 1
			w.Items[i] = w.Items[lastIndex]
			w.Items = w.Items[:lastIndex]
			w.UpdatedAt = time.Now()
			return nil
		}
	}

	return errors.New("item not found in wishlist")
}

// RemoveItemByProduct removes a product from the wishlist by product ID
func (w *Wishlist) RemoveItemByProduct(productID primitive.ObjectID) error {
	for i, item := range w.Items {
		if item.ProductID == productID {
			// Remove item by replacing it with the last item and truncating the slice
			lastIndex := len(w.Items) - 1
			w.Items[i] = w.Items[lastIndex]
			w.Items = w.Items[:lastIndex]
			w.UpdatedAt = time.Now()
			return nil
		}
	}

	return errors.New("item not found in wishlist")
}

// ClearWishlist removes all items from the wishlist
func (w *Wishlist) ClearWishlist() {
	w.Items = []*WishlistItem{}
	w.UpdatedAt = time.Now()
}

// ClearItems removes all items from the wishlist (alias for ClearWishlist)
func (w *Wishlist) ClearItems() {
	w.ClearWishlist()
}

// ContainsProduct checks if a product is in the wishlist
func (w *Wishlist) ContainsProduct(productID primitive.ObjectID) bool {
	for _, item := range w.Items {
		if item.ProductID == productID {
			return true
		}
	}

	return false
}
